name = input ("Enter your name:")
month= input ("Enter your birth month:")
day= input ("Enter birthdate of the month(eg.06):")
year= input ("Enter birth year(eg.2022):")
print (name+", Your birthday is on",month,day+',',year,"!")